spring.application.name=api-gateway
server.port=8500

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# --- CONFIGURACIÓN DE SWAGGER URLS ---
springdoc.swagger-ui.urls[0].name=Prevision
springdoc.swagger-ui.urls[0].url=/v3/api-docs/prevision
springdoc.swagger-ui.urls[1].name=Paciente
springdoc.swagger-ui.urls[1].url=/v3/api-docs/paciente
springdoc.swagger-ui.urls[2].name=Historial Medico
springdoc.swagger-ui.urls[2].url=/v3/api-docs/historial
springdoc.swagger-ui.urls[3].name=Factura
springdoc.swagger-ui.urls[3].url=/v3/api-docs/factura
springdoc.swagger-ui.urls[4].name=API Gateway
springdoc.swagger-ui.urls[4].url=/v3/api-docs
springdoc.swagger-ui.urls[5].name=Habitacion
springdoc.swagger-ui.urls[5].url=/v3/api-docs/habitacion
springdoc.swagger-ui.urls[6].name=Staff
springdoc.swagger-ui.urls[6].url=/v3/api-docs/staffv2
springdoc.swagger-ui.urls[7].name=Examenes
springdoc.swagger-ui.urls[7].url=/v3/api-docs/examenes
springdoc.swagger-ui.urls[8].name=Bono
springdoc.swagger-ui.urls[8].url=/v3/api-docs/bono

# --- ENRUTAMIENTO API GATEWAY (SPRING CLOUD GATEWAY) ---
spring.cloud.gateway.server.webmvc.routes[0].id=prevision
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://prevision
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/previsiones/**

spring.cloud.gateway.server.webmvc.routes[1].id=paciente
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://Paciente
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/pacientes/**

spring.cloud.gateway.server.webmvc.routes[2].id=historial
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://HistorialMedico
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/historialMedico/**

spring.cloud.gateway.server.webmvc.routes[3].id=factura
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://factura
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/facturas/**

spring.cloud.gateway.server.webmvc.routes[4].id=staffv2
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://Staffv2
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/staff/**

spring.cloud.gateway.server.webmvc.routes[5].id=habitacion
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://Habitacion
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/habitacion/**

spring.cloud.gateway.server.webmvc.routes[6].id=especialidad
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://Staffv2
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/especialidad/**

spring.cloud.gateway.server.webmvc.routes[7].id=examenes
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://examenes2
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/examenes/**

spring.cloud.gateway.server.webmvc.routes[8].id=bono
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://bono
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/bono/**

# --- BASE DE DATOS Y SEGURIDAD ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hp_gateway_vm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
jwt.expiration=86400000