spring.application.name=api-gateway
server.port=8500

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.mvc.routes[0].id=prevision
spring.cloud.gateway.mvc.routes[0].uri=lb://prevision
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/previsiones/**

spring.cloud.gateway.mvc.routes[1].id=paciente
spring.cloud.gateway.mvc.routes[1].uri=lb://Paciente
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/pacientes/**

spring.cloud.gateway.mvc.routes[2].id=historial
spring.cloud.gateway.mvc.routes[2].uri=lb://Historial_Medico
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/historialMedico/**

spring.cloud.gateway.mvc.routes[3].id=staffv2
spring.cloud.gateway.mvc.routes[3].uri=lb://Staffv2
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/v2/staff/**

spring.cloud.gateway.server.webmvc.routes[4].id=factura
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://factura
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/facturas/**